### ISSUE TITLE
Plugin error: error occurred in getTabsProps

### ISSUE THREAD

**Issue by linkurzweg** [sdomino/hyperterm-tab-cwd#2]
The plugin is not working for me.
I get the error message

`Plugin error: hyperterm-tab-cwd: error occurred in getTabsProps` every time I open hyper or a new tab.

I'm on MacOS Sierra with hyper v0.8.3.

**Comment by joeyvandijk** [comment]
Same here with hyper v0.8.3 &  MacOS Sierra.

**Comment by sdomino** [comment]
Thanks for reporting this issue. I've provided my "solution" in #1. I'll reopen that issue for posterity.
